Repository metwork-framework/mfextaddon_scientific, pull requests merged in 2019-04, with the labels that each got.

#4 [WIP]feat: first ok version of new mfextaddon scientific
  layers/layer4_python2_scientific/.layerapi2_dependencies
  layers/layer4_python2_scientific/0100_pyke/Makefile
  layers/layer4_python2_scientific/0500_extra_packages/Makefile
  layers/layer4_python2_scientific/0500_extra_packages/requirements-to-freeze.txt
  layers/layer4_python2_scientific/0500_extra_packages/requirements2.txt
  layers/layer4_python2_scientific/0501_pygraphviz/Makefile
  layers/layer4_python2_scientific/0501_pygraphviz/Makefile.mk
  layers/layer4_python2_scientific/0502_Fiona/Makefile
  layers/layer4_python2_scientific/0510_cf-units/Makefile
  layers/layer4_python2_scientific/0611_eccodes/Makefile
  layers/layer4_python2_scientific/0621_magics/Makefile
  layers/layer4_python2_scientific/0630_esmf/Makefile
  layers/layer4_python2_scientific/0640_cartopy/Makefile
  layers/layer4_python2_scientific/0650_iris/Makefile
  layers/layer4_python3_scientific/.layerapi2_dependencies
  layers/layer4_python3_scientific/0100_pyke/Makefile
  layers/layer4_python3_scientific/0500_extra_packages/Makefile
  layers/layer4_python3_scientific/0500_extra_packages/Makefile.mk
  layers/layer4_python3_scientific/0500_extra_packages/requirements-to-freeze.txt
  layers/layer4_python3_scientific/0500_extra_packages/requirements3.txt
  layers/layer4_python3_scientific/0501_pygraphviz/Makefile
  layers/layer4_python3_scientific/0501_pygraphviz/Makefile.mk
  layers/layer4_python3_scientific/0502_Fiona/Makefile
  layers/layer4_python3_scientific/0510_cf-units/Makefile
  layers/layer4_python3_scientific/0611_eccodes/Makefile
  layers/layer4_python3_scientific/0621_magics/Makefile
  layers/layer4_python3_scientific/0630_esmf/Makefile
  layers/layer4_python3_scientific/0640_cartopy/Makefile
  layers/layer4_python3_scientific/0650_iris/Makefile
Labels: Merge Now, Status: Revision Needed

#5 refactor: add numpy (previously in mfext) as a prerequired python pac…
  layers/layer4_python2_scientific/0499_prereq_extra_packages/Makefile
  layers/layer4_python2_scientific/0499_prereq_extra_packages/Makefile.mk
  layers/layer4_python2_scientific/0499_prereq_extra_packages/prerequirements-to-freeze.txt
  layers/layer4_python2_scientific/0499_prereq_extra_packages/prerequirements2.txt
  layers/layer4_python2_scientific/0499_prereq_extra_packages/requirements-to-freeze.txt
  layers/layer4_python2_scientific/0499_prereq_extra_packages/requirements2.txt
  layers/layer4_python3_scientific/0499_prereq_extra_packages/Makefile
  layers/layer4_python3_scientific/0499_prereq_extra_packages/Makefile.mk
  layers/layer4_python3_scientific/0499_prereq_extra_packages/prerequirements-to-freeze.txt
  layers/layer4_python3_scientific/0499_prereq_extra_packages/prerequirements3.txt
  layers/layer4_python3_scientific/0499_prereq_extra_packages/requirements-to-freeze.txt
  layers/layer4_python3_scientific/0499_prereq_extra_packages/requirements3.txt
Labels: Status: Revision Needed

#6 feat: add integration tests in mfextaddon scientific (previously in m…
  integration_tests/0003_test_import_python2_scientific/.layerapi2_dependencies
  integration_tests/0003_test_import_python2_scientific/import_python2_scientific.py
  integration_tests/0003_test_import_python2_scientific/test_import_python2_scientific.sh
  integration_tests/0003_test_import_python3_scientific/.layerapi2_dependencies
  integration_tests/0003_test_import_python3_scientific/import_python3_scientific.py
  integration_tests/0003_test_import_python3_scientific/test_import_python3_scientific.sh
Labels: Status: Revision Needed

#7 build: remove python prerequirement files (useless now)
  layers/layer4_python2_scientific/0499_prereq_extra_packages/prerequirements-to-freeze.txt
  layers/layer4_python2_scientific/0499_prereq_extra_packages/prerequirements2.txt
  layers/layer4_python2_scientific/0500_extra_packages/prerequirements-to-freeze.txt
  layers/layer4_python2_scientific/0500_extra_packages/prerequirements2.txt
  layers/layer4_python3_scientific/0499_prereq_extra_packages/prerequirements-to-freeze.txt
  layers/layer4_python3_scientific/0499_prereq_extra_packages/prerequirements3.txt
  layers/layer4_python3_scientific/0500_extra_packages/prerequirements-to-freeze.txt
  layers/layer4_python3_scientific/0500_extra_packages/prerequirements3.txt
Labels: Status: Revision Needed

#9 [WIP] feat: add cfgrib and xarray
  layers/layer4_python3_scientific/0500_extra_packages/requirements-to-freeze.txt
  layers/layer4_python3_scientific/0500_extra_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed
