Repository metwork-framework/mfextaddon_scientific, pull requests merged in 2019-08, with the labels that each got.

#30 build: change graphviz build options (like in devtools)
  layers/layer1_scientific/0026_graphviz/Makefile.mk
Labels: Merge Now, Status: Review Needed

#32 docs: Update MFEXT Scientific Addon documentation
  .gitignore
  doc/index.rst
  doc/mfextaddon_scientific_intro.md
  layer_custom.md
Labels: Status: Review Needed

#34 docs: Fix typo
  .gitignore
  doc/index.rst
  layer_custom.md
  layers/layer4_python2_scientific/layer_custom.md
  layers/layer4_python3_scientific/layer_custom.md
Labels: Merge Now, Status: Review Needed

#33 feat: upgrade ESMF (python3 support is now working) and NCO (for comp…
  integration_tests/0003_test_import_python2_scientific/import_python2_scientific.py
  integration_tests/0003_test_import_python3_scientific/import_python3_scientific.py
  layers/layer1_scientific/0015_nco/Makefile.mk
  layers/layer1_scientific/0015_nco/sources
  layers/layer1_scientific/0050_esmf/Makefile.mk
  layers/layer1_scientific/0050_esmf/sources
  layers/layer4_python2_scientific/0630_esmf/Makefile.mk
  layers/layer4_python2_scientific/0630_esmf/sources
  layers/layer4_python3_scientific/0630_esmf/Makefile.mk
  layers/layer4_python3_scientific/0630_esmf/sources
Labels: Merge Now, Status: Review Needed

#37 Revert "feat: upgrade ESMF (python3 support is now working) and NCO (…
  integration_tests/0003_test_import_python2_scientific/import_python2_scientific.py
  integration_tests/0003_test_import_python3_scientific/import_python3_scientific.py
  layers/layer1_scientific/0015_nco/Makefile.mk
  layers/layer1_scientific/0015_nco/sources
  layers/layer1_scientific/0050_esmf/Makefile.mk
  layers/layer1_scientific/0050_esmf/sources
  layers/layer4_python2_scientific/0630_esmf/Makefile.mk
  layers/layer4_python2_scientific/0630_esmf/sources
  layers/layer4_python3_scientific/0630_esmf/Makefile.mk
  layers/layer4_python3_scientific/0630_esmf/sources
Labels: Merge Now

#38 Revert "Revert "feat: upgrade ESMF (python3 support is now working) a…
  integration_tests/0003_test_import_python2_scientific/import_python2_scientific.py
  integration_tests/0003_test_import_python3_scientific/import_python3_scientific.py
  layers/layer1_scientific/0015_nco/Makefile.mk
  layers/layer1_scientific/0015_nco/sources
  layers/layer1_scientific/0050_esmf/Makefile.mk
  layers/layer1_scientific/0050_esmf/sources
  layers/layer4_python2_scientific/0630_esmf/Makefile.mk
  layers/layer4_python2_scientific/0630_esmf/sources
  layers/layer4_python3_scientific/0630_esmf/Makefile.mk
  layers/layer4_python3_scientific/0630_esmf/sources
Labels: Merge Now, Status: Review Needed

#39 Move netcdff to addon scientific
  .gitignore
  layers/layer1_scientific/.system_dependencies
  layers/layer1_scientific/0010_netcdf_fortran/Makefile
  layers/layer1_scientific/0010_netcdf_fortran/Makefile.mk
  layers/layer1_scientific/0010_netcdf_fortran/sources
  layers/layer1_scientific/0050_esmf/Makefile.mk
  layers/layer1_scientific/0050_esmf/esmf-build-with-netcdff-not-with-netcdfc.patch
  layers/layer1_scientific/0050_esmf/patches
  layers/layer4_python2_scientific/0611_eccodes/Makefile.mk
  layers/layer4_python2_scientific/0630_esmf/Makefile.mk
  layers/layer4_python3_scientific/0630_esmf/Makefile.mk
Labels: Status: Review Needed

#41 build: add system dependencies tests (as in mfext but the build doesn…
  .gitignore
  integration_tests/0005_suspicious_dependencies/test.sh
  integration_tests/0006_system_extra_dependencies/list.txt
  integration_tests/0006_system_extra_dependencies/test.sh
Labels: Merge Now, Status: Review Needed

#40 build: add dependency to layer tcltk@mfext
  layers/layer4_python2_scientific/.layerapi2_dependencies
  layers/layer4_python3_scientific/.layerapi2_dependencies
Labels: Merge Now, Status: Review Needed

#42 build: add new system dependencies (moved from mfext)
  layers/layer1_scientific/.system_dependencies
Labels: Merge Now, Status: Review Needed
