Repository metwork-framework/mfextaddon_scientific, pull requests merged in 2020-01, with the labels that each got.

#85 build: update components.md
  .metwork-framework/components.md
Labels: Status: Review Needed

#86 build: update components.md
  .metwork-framework/components.md
Labels: Status: Review Needed

#87 Update centos8
  .metwork-framework/components.md
  layers/layer1_scientific/0040_imagemagick6/Makefile.mk
  layers/layer1_scientific/0040_imagemagick6/sources
Labels: Status: Review Needed

#89 Update centos8b
  .metwork-framework/components.md
  layers/layer1_scientific/0004_pngquant/Makefile.mk
  layers/layer1_scientific/0004_pngquant/sources
  layers/layer1_scientific/0010_netcdf_fortran/Makefile.mk
  layers/layer1_scientific/0010_netcdf_fortran/sources
  layers/layer1_scientific/0040_imagemagick6/Makefile.mk
  layers/layer1_scientific/0040_imagemagick6/sources
  layers/layer4_python2_scientific/0498_prereq_extra_packages/Makefile
  layers/layer4_python2_scientific/0498_prereq_extra_packages/Makefile.mk
  layers/layer4_python2_scientific/0498_prereq_extra_packages/requirements-to-freeze.txt
  layers/layer4_python2_scientific/0498_prereq_extra_packages/requirements2.txt
  layers/layer4_python2_scientific/0499_extra_packages/Makefile
  layers/layer4_python2_scientific/0499_extra_packages/Makefile.mk
  layers/layer4_python2_scientific/0499_extra_packages/requirements-to-freeze.txt
  layers/layer4_python2_scientific/0499_extra_packages/requirements2.txt
  layers/layer4_python2_scientific/0500_scl_extra_packages/Makefile
  layers/layer4_python2_scientific/0500_scl_extra_packages/Makefile.mk
  layers/layer4_python2_scientific/0500_scl_extra_packages/requirements-to-freeze.txt
  layers/layer4_python2_scientific/0500_scl_extra_packages/requirements2.txt
  layers/layer4_python2_scientific/0502_Fiona/Makefile.mk
  layers/layer4_python2_scientific/0502_Fiona/sources
  layers/layer4_python3_scientific/0498_prereq_extra_packages/Makefile
  layers/layer4_python3_scientific/0498_prereq_extra_packages/Makefile.mk
  layers/layer4_python3_scientific/0498_prereq_extra_packages/requirements-to-freeze.txt
  layers/layer4_python3_scientific/0498_prereq_extra_packages/requirements3.txt
  layers/layer4_python3_scientific/0499_extra_packages/Makefile
  layers/layer4_python3_scientific/0499_extra_packages/Makefile.mk
  layers/layer4_python3_scientific/0499_extra_packages/requirements-to-freeze.txt
  layers/layer4_python3_scientific/0499_extra_packages/requirements3.txt
  layers/layer4_python3_scientific/0500_scl_extra_packages/Makefile
  layers/layer4_python3_scientific/0500_scl_extra_packages/Makefile.mk
  layers/layer4_python3_scientific/0500_scl_extra_packages/requirements-to-freeze.txt
  layers/layer4_python3_scientific/0500_scl_extra_packages/requirements3.txt
  layers/layer4_python3_scientific/0502_Fiona/Makefile.mk
  layers/layer4_python3_scientific/0502_Fiona/sources
Labels: Merge Now, Status: Review Needed

#90 docs: mkdocs migration
  .gitignore
  doc/Makefile
  doc/Makefile.mk
  doc/_images/logo-metwork.png
  doc/_images/metwork.ico
  doc/_static/css/override_theme.css
  doc/_static/empty
  doc/_templates/breadcrumbs.html
  doc/_templates/layout.html
  doc/changelogs.tmpl
  doc/conf.py
  doc/index.rst
  docs/10-whatisit.md
  docs/20-quickstart.md
Labels: Status: Review Needed

#91 build: new readme
  .metwork-framework/README.md
Labels: Merge Now

#92 feat: build all mfextaddon_scientific with devtoolset-8 (gcc-8)
  layers/layer1_scientific/0007_harfbuzz/Makefile.mk
  layers/layer1_scientific/0010_netcdf_fortran/Makefile.mk
  layers/layer1_scientific/0035_magics/Makefile.mk
  layers/layer1_scientific/0038_metview/Makefile.mk
  layers/layer1_scientific/0050_esmf/Makefile.mk
  layers/layer1_scientific/0060_cdo/Makefile.mk
  layers/layer4_python2_scientific/0499_extra_packages/requirements-to-freeze.txt
  layers/layer4_python2_scientific/0499_extra_packages/requirements2.txt
  layers/layer4_python2_scientific/0500_scl_extra_packages/Makefile
  layers/layer4_python2_scientific/0500_scl_extra_packages/Makefile.mk
  layers/layer4_python2_scientific/0500_scl_extra_packages/requirements-to-freeze.txt
  layers/layer4_python2_scientific/0500_scl_extra_packages/requirements2.txt
  layers/layer4_python2_scientific/0630_esmf/Makefile.mk
  layers/layer4_python3_scientific/0499_extra_packages/requirements-to-freeze.txt
  layers/layer4_python3_scientific/0499_extra_packages/requirements3.txt
  layers/layer4_python3_scientific/0500_scl_extra_packages/Makefile
  layers/layer4_python3_scientific/0500_scl_extra_packages/Makefile.mk
  layers/layer4_python3_scientific/0500_scl_extra_packages/requirements-to-freeze.txt
  layers/layer4_python3_scientific/0500_scl_extra_packages/requirements3.txt
  layers/layer4_python3_scientific/0630_esmf/Makefile.mk
Labels: Status: Review Needed

#93 build: replace libgfortran4 by libgfortran5 (gcc-8)
  layers/layer0_scientific_system_libraries/0001_libraries/libraries.txt
Labels: Status: Review Needed

#94 build: replace libgfortran4 by libgfortran5 (gcc-8)
  layers/layer1_scientific/.system_dependencies
Labels: Status: Review Needed

#95 Build with devtoolset8
  layers/layer1_scientific/0040_imagemagick6/aligned_alloc_is_not_defined.patch
  layers/layer1_scientific/0040_imagemagick6/patches
Labels: Status: Review Needed
